title: 熵降
subtitle: Decrease In Entropy
description: >-
  记录对科技的想法，用最平凡的文字分享知识技巧。
  Blog what I though about tech stuff, trying with the most plain words to share knowledge.
author: Jiahao
email: me@djh.im
footer_title: For Your Infomation
baseurl: ""
url: https://blog.djh.im
logo: /assets/trusty-logo-20171119.png
host: blog.djh.im
port: 80
version: v0.0.1

# social network spec
github_username:  delight09
steam_username:  dummyred
v2ex_username:  imdjh
reddit_username:  imdjh
stackoverflow_username: 4349454
xiami_username: 18512723

# SEO
social:
  name: Jiahao Dai
  links:
    - https://github.com/delight09
    - https://reddit.com/u/imdjh
    - https://www.v2ex.com/member/imdjh
    - https://stackoverflow.com/users/4349454/jiahao-d

# Build settings
markdown: kramdown
theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
